# GoReleaser v2 config. See https://goreleaser.com/2.0/
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gossm
    binary: gossm
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.gossmVersion={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats: ['tar.gz', 'zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: darwin
        formats: ['tar.gz']
      - goos: linux
        formats: ['tar.gz']
      - goos: windows
        formats: ['tar.gz', 'zip']

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: glieske
    name: gossm

